### ISSUE TITLE
LAMMPS compatibility

### ISSUE THREAD

**Issue by mutingx** [njzjz/deepmd-gnn#13]
I'm trying to run LAMMPS with models trained by deepmd-mace. The deepmd-mace was installed following the README.md and it did work. But when running `lmp -i in.lmp`, it failed with the following message:
```
 DeePMD-kit C API Error: DeePMD-kit Error: incompatable model: version 0.0 in graph, but version 1.1
 Last command: pair_style   deepmd frozen_model.pth
```
Should I recompile the `dp` part or the `lmp` part? How to recompile LAMMPS with the new "libdeepmd_mace.so"?
Best wishes.

**Comment by njzjz** [comment]
> incompatable model: version 0.0 in graph, but version 1.1

This error is from the TensorFlow backend. Did you use an old version?

**Comment by njzjz** [comment]
Please check whether you use the latest code on the [devel](https://github.com/deepmodeling/deepmd-kit/tree/devel) branch to compile the C++ interface. The plugin support has not been released to any release version.

**Comment by mutingx** [comment]
I used the released version. Thanks for your help! That's quite helpful and I will try the latest codes

**Comment by njzjz** [comment]
v3.0.0b4 has been released, so it should not be a problem anymore.
